version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=production
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - sqlite_data:/data
    command: tail -f /dev/null

volumes:
  sqlite_data:
