services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./requests.db:/app/requests.db
      - ./requests.log:/app/requests.log
    environment:
      - GO_ENV=production
